Снчала программа выбросит ExceptionInInitializerError исключение, так как мы самостоятельно выбрасываем
исключение в статическом блоке инициализации, что и приводит к такому результату.
Потом мы пройдем проверку в if`e, так как причиной ошибки был объект класса MyException
Из-за того, что нарушена инициализация класса MyException падает исключение NoClassDefFoundError